<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\Provincia;
use App\Models\Canton;

class ProvinciaCantonSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        Provincia::create(['nombre' => 'AZUAY']);
        Provincia::create(['nombre' => 'BOLIVAR']);
        Provincia::create(['nombre' => 'CAÑAR']);
        Provincia::create(['nombre' => 'CARCHI']);
        Provincia::create(['nombre' => 'COTOPAXI']);
        Provincia::create(['nombre' => 'CHIMBORAZO']);
        Provincia::create(['nombre' => 'EL ORO']);
        Provincia::create(['nombre' => 'ESMERALDAS']);
        Provincia::create(['nombre' => 'GUAYAS']);
        Provincia::create(['nombre' => 'IMBABURA']);
        Provincia::create(['nombre' => 'LOJA']);
        Provincia::create(['nombre' => 'LOS RIOS']);
        Provincia::create(['nombre' => 'MANABI']);
        Provincia::create(['nombre' => 'MORONA SANTIAGO']);
        Provincia::create(['nombre' => 'NAPO']);
        Provincia::create(['nombre' => 'PASTAZA']);
        Provincia::create(['nombre' => 'PICHINCHA']);
        Provincia::create(['nombre' => 'TUNGURAHUA']);
        Provincia::create(['nombre' => 'ZAMORA CHINCHIPE']);
        Provincia::create(['nombre' => 'GALAPAGOS']);
        Provincia::create(['nombre' => 'SUCUMBIOS']);
        Provincia::create(['nombre' => 'ORELLANA']);
        Provincia::create(['nombre' => 'SANTO DOMINGO DE LOS TSACHILAS']);
        Provincia::create(['nombre' => 'SANTA ELENA']);

        Canton::create(['nombre' => 'GIRÓN' , 'idProvincia' => 1]);
        Canton::create(['nombre' => 'GUALACEO' , 'idProvincia' => 1]);
        Canton::create(['nombre' => 'NABÓN' , 'idProvincia' => 1]);
        Canton::create(['nombre' => 'PAUTE' , 'idProvincia' => 1]);
        Canton::create(['nombre' => 'PUCARA' , 'idProvincia' => 1]);
        Canton::create(['nombre' => 'SAN FERNANDO' , 'idProvincia' => 1]);
        Canton::create(['nombre' => 'SANTA ISABEL' , 'idProvincia' => 1]);
        Canton::create(['nombre' => 'SIGSIG' , 'idProvincia' => 1]);
        Canton::create(['nombre' => 'OÑA' , 'idProvincia' => 1]);
        Canton::create(['nombre' => 'CHORDELEG' , 'idProvincia' => 1]);
        Canton::create(['nombre' => 'EL PAN' , 'idProvincia' => 1]);
        Canton::create(['nombre' => 'SEVILLA DE ORO' , 'idProvincia' => 1]);
        Canton::create(['nombre' => 'GUACHAPALA' , 'idProvincia' => 1]);
        Canton::create(['nombre' => 'CAMILO PONCE ENRÍQUEZ' , 'idProvincia' => 1]);
        Canton::create(['nombre' => 'GUARANDA' , 'idProvincia' => 2]);
        Canton::create(['nombre' => 'CHILLANES' , 'idProvincia' => 2]);
        Canton::create(['nombre' => 'CHIMBO' , 'idProvincia' => 2]);
        Canton::create(['nombre' => 'ECHEANDÍA' , 'idProvincia' => 2]);
        Canton::create(['nombre' => 'SAN MIGUEL' , 'idProvincia' => 2]);
        Canton::create(['nombre' => 'CALUMA' , 'idProvincia' => 2]);
        Canton::create(['nombre' => 'LAS NAVES' , 'idProvincia' => 2]);
        Canton::create(['nombre' => 'AZOGUES' , 'idProvincia' => 3]);
        Canton::create(['nombre' => 'BIBLIÁN' , 'idProvincia' => 3]);
        Canton::create(['nombre' => 'CAÑAR' , 'idProvincia' => 3]);
        Canton::create(['nombre' => 'LA TRONCAL' , 'idProvincia' => 3]);
        Canton::create(['nombre' => 'EL TAMBO' , 'idProvincia' => 3]);
        Canton::create(['nombre' => 'DÉLEG' , 'idProvincia' => 3]);
        Canton::create(['nombre' => 'SUSCAL' , 'idProvincia' => 3]);
        Canton::create(['nombre' => 'TULCÁN' , 'idProvincia' => 4]);
        Canton::create(['nombre' => 'BOLÍVAR' , 'idProvincia' => 4]);
        Canton::create(['nombre' => 'ESPEJO' , 'idProvincia' => 4]);
        Canton::create(['nombre' => 'MIRA' , 'idProvincia' => 4]);
        Canton::create(['nombre' => 'MONTÚFAR' , 'idProvincia' => 4]);
        Canton::create(['nombre' => 'SAN PEDRO DE HUACA' , 'idProvincia' => 4]);
        Canton::create(['nombre' => 'LATACUNGA' , 'idProvincia' => 5]);
        Canton::create(['nombre' => 'LA MANÁ' , 'idProvincia' => 5]);
        Canton::create(['nombre' => 'PANGUA' , 'idProvincia' => 5]);
        Canton::create(['nombre' => 'PUJILI' , 'idProvincia' => 5]);
        Canton::create(['nombre' => 'SALCEDO' , 'idProvincia' => 5]);
        Canton::create(['nombre' => 'SAQUISILÍ' , 'idProvincia' => 5]);
        Canton::create(['nombre' => 'SIGCHOS' , 'idProvincia' => 5]);
        Canton::create(['nombre' => 'RIOBAMBA' , 'idProvincia' => 6]);
        Canton::create(['nombre' => 'ALAUSI' , 'idProvincia' => 6]);
        Canton::create(['nombre' => 'COLTA' , 'idProvincia' => 6]);
        Canton::create(['nombre' => 'CHAMBO' , 'idProvincia' => 6]);
        Canton::create(['nombre' => 'CHUNCHI' , 'idProvincia' => 6]);
        Canton::create(['nombre' => 'GUAMOTE' , 'idProvincia' => 6]);
        Canton::create(['nombre' => 'GUANO' , 'idProvincia' => 6]);
        Canton::create(['nombre' => 'PALLATANGA' , 'idProvincia' => 6]);
        Canton::create(['nombre' => 'PENIPE' , 'idProvincia' => 6]);
        Canton::create(['nombre' => 'CUMANDÁ' , 'idProvincia' => 6]);
        Canton::create(['nombre' => 'MACHALA' , 'idProvincia' => 7]);
        Canton::create(['nombre' => 'ARENILLAS' , 'idProvincia' => 7]);
        Canton::create(['nombre' => 'ATAHUALPA' , 'idProvincia' => 7]);
        Canton::create(['nombre' => 'BALSAS' , 'idProvincia' => 7]);
        Canton::create(['nombre' => 'CHILLA' , 'idProvincia' => 7]);
        Canton::create(['nombre' => 'EL GUABO' , 'idProvincia' => 7]);
        Canton::create(['nombre' => 'HUAQUILLAS' , 'idProvincia' => 7]);
        Canton::create(['nombre' => 'MARCABELÍ' , 'idProvincia' => 7]);
        Canton::create(['nombre' => 'PASAJE' , 'idProvincia' => 7]);
        Canton::create(['nombre' => 'PIÑAS' , 'idProvincia' => 7]);
        Canton::create(['nombre' => 'PORTOVELO' , 'idProvincia' => 7]);
        Canton::create(['nombre' => 'SANTA ROSA' , 'idProvincia' => 7]);
        Canton::create(['nombre' => 'ZARUMA' , 'idProvincia' => 7]);
        Canton::create(['nombre' => 'LAS LAJAS' , 'idProvincia' => 7]);
        Canton::create(['nombre' => 'ESMERALDAS' , 'idProvincia' => 8]);
        Canton::create(['nombre' => 'ELOY ALFARO' , 'idProvincia' => 8]);
        Canton::create(['nombre' => 'MUISNE' , 'idProvincia' => 8]);
        Canton::create(['nombre' => 'QUININDÉ' , 'idProvincia' => 8]);
        Canton::create(['nombre' => 'SAN LORENZO' , 'idProvincia' => 8]);
        Canton::create(['nombre' => 'ATACAMES' , 'idProvincia' => 8]);
        Canton::create(['nombre' => 'RIOVERDE' , 'idProvincia' => 8]);
        Canton::create(['nombre' => 'LA CONCORDIA' , 'idProvincia' => 8]);
        Canton::create(['nombre' => 'GUAYAQUIL' , 'idProvincia' => 9]);
        Canton::create(['nombre' => 'ALFREDO BAQUERIZO MORENO (JUJÁN)' , 'idProvincia' => 9]);
        Canton::create(['nombre' => 'BALAO' , 'idProvincia' => 9]);
        Canton::create(['nombre' => 'BALZAR' , 'idProvincia' => 9]);
        Canton::create(['nombre' => 'COLIMES' , 'idProvincia' => 9]);
        Canton::create(['nombre' => 'DAULE' , 'idProvincia' => 9]);
        Canton::create(['nombre' => 'DURÁN' , 'idProvincia' => 9]);
        Canton::create(['nombre' => 'EL EMPALME' , 'idProvincia' => 9]);
        Canton::create(['nombre' => 'EL TRIUNFO' , 'idProvincia' => 9]);
        Canton::create(['nombre' => 'MILAGRO' , 'idProvincia' => 9]);
        Canton::create(['nombre' => 'NARANJAL' , 'idProvincia' => 9]);
        Canton::create(['nombre' => 'NARANJITO' , 'idProvincia' => 9]);
        Canton::create(['nombre' => 'PALESTINA' , 'idProvincia' => 9]);
        Canton::create(['nombre' => 'PEDRO CARBO' , 'idProvincia' => 9]);
        Canton::create(['nombre' => 'SAMBORONDÓN' , 'idProvincia' => 9]);
        Canton::create(['nombre' => 'SANTA LUCÍA' , 'idProvincia' => 9]);
        Canton::create(['nombre' => 'SALITRE (URBINA JADO)' , 'idProvincia' => 9]);
        Canton::create(['nombre' => 'SAN JACINTO DE YAGUACHI' , 'idProvincia' => 9]);
        Canton::create(['nombre' => 'PLAYAS' , 'idProvincia' => 9]);
        Canton::create(['nombre' => 'SIMÓN BOLÍVAR' , 'idProvincia' => 9]);
        Canton::create(['nombre' => 'CORONEL MARCELINO MARIDUEÑA' , 'idProvincia' => 9]);
        Canton::create(['nombre' => 'LOMAS DE SARGENTILLO' , 'idProvincia' => 9]);
        Canton::create(['nombre' => 'NOBOL' , 'idProvincia' => 9]);
        Canton::create(['nombre' => 'GENERAL ANTONIO ELIZALDE' , 'idProvincia' => 9]);
        Canton::create(['nombre' => 'ISIDRO AYORA' , 'idProvincia' => 9]);
        Canton::create(['nombre' => 'IBARRA' , 'idProvincia' => 10]);
        Canton::create(['nombre' => 'ANTONIO ANTE' , 'idProvincia' => 10]);
        Canton::create(['nombre' => 'COTACACHI' , 'idProvincia' => 10]);
        Canton::create(['nombre' => 'OTAVALO' , 'idProvincia' => 10]);
        Canton::create(['nombre' => 'PIMAMPIRO' , 'idProvincia' => 10]);
        Canton::create(['nombre' => 'SAN MIGUEL DE URCUQUÍ' , 'idProvincia' => 10]);
        Canton::create(['nombre' => 'LOJA' , 'idProvincia' => 11]);
        Canton::create(['nombre' => 'CALVAS' , 'idProvincia' => 11]);
        Canton::create(['nombre' => 'CATAMAYO' , 'idProvincia' => 11]);
        Canton::create(['nombre' => 'CELICA' , 'idProvincia' => 11]);
        Canton::create(['nombre' => 'CHAGUARPAMBA' , 'idProvincia' => 11]);
        Canton::create(['nombre' => 'ESPÍNDOLA' , 'idProvincia' => 11]);
        Canton::create(['nombre' => 'GONZANAMÁ' , 'idProvincia' => 11]);
        Canton::create(['nombre' => 'MACARÁ' , 'idProvincia' => 11]);
        Canton::create(['nombre' => 'PALTAS' , 'idProvincia' => 11]);
        Canton::create(['nombre' => 'PUYANGO' , 'idProvincia' => 11]);
        Canton::create(['nombre' => 'SARAGURO' , 'idProvincia' => 11]);
        Canton::create(['nombre' => 'SOZORANGA' , 'idProvincia' => 11]);
        Canton::create(['nombre' => 'ZAPOTILLO' , 'idProvincia' => 11]);
        Canton::create(['nombre' => 'PINDAL' , 'idProvincia' => 11]);
        Canton::create(['nombre' => 'QUILANGA' , 'idProvincia' => 11]);
        Canton::create(['nombre' => 'OLMEDO' , 'idProvincia' => 11]);
        Canton::create(['nombre' => 'BABAHOYO' , 'idProvincia' => 12]);
        Canton::create(['nombre' => 'BABA' , 'idProvincia' => 12]);
        Canton::create(['nombre' => 'MONTALVO' , 'idProvincia' => 12]);
        Canton::create(['nombre' => 'PUEBLOVIEJO' , 'idProvincia' => 12]);
        Canton::create(['nombre' => 'QUEVEDO' , 'idProvincia' => 12]);
        Canton::create(['nombre' => 'URDANETA' , 'idProvincia' => 12]);
        Canton::create(['nombre' => 'VENTANAS' , 'idProvincia' => 12]);
        Canton::create(['nombre' => 'VÍNCES' , 'idProvincia' => 12]);
        Canton::create(['nombre' => 'PALENQUE' , 'idProvincia' => 12]);
        Canton::create(['nombre' => 'BUENA FÉ' , 'idProvincia' => 12]);
        Canton::create(['nombre' => 'VALENCIA' , 'idProvincia' => 12]);
        Canton::create(['nombre' => 'MOCACHE' , 'idProvincia' => 12]);
        Canton::create(['nombre' => 'QUINSALOMA' , 'idProvincia' => 12]);
        Canton::create(['nombre' => 'PORTOVIEJO' , 'idProvincia' => 13]);
        Canton::create(['nombre' => 'BOLÍVAR' , 'idProvincia' => 13]);
        Canton::create(['nombre' => 'CHONE' , 'idProvincia' => 13]);
        Canton::create(['nombre' => 'EL CARMEN' , 'idProvincia' => 13]);
        Canton::create(['nombre' => 'FLAVIO ALFARO' , 'idProvincia' => 13]);
        Canton::create(['nombre' => 'JIPIJAPA' , 'idProvincia' => 13]);
        Canton::create(['nombre' => 'JUNÍN' , 'idProvincia' => 13]);
        Canton::create(['nombre' => 'MANTA' , 'idProvincia' => 13]);
        Canton::create(['nombre' => 'MONTECRISTI' , 'idProvincia' => 13]);
        Canton::create(['nombre' => 'PAJÁN' , 'idProvincia' => 13]);
        Canton::create(['nombre' => 'PICHINCHA' , 'idProvincia' => 13]);
        Canton::create(['nombre' => 'ROCAFUERTE' , 'idProvincia' => 13]);
        Canton::create(['nombre' => 'SANTA ANA' , 'idProvincia' => 13]);
        Canton::create(['nombre' => 'SUCRE' , 'idProvincia' => 13]);
        Canton::create(['nombre' => 'TOSAGUA' , 'idProvincia' => 13]);
        Canton::create(['nombre' => '24 DE MAYO' , 'idProvincia' => 13]);
        Canton::create(['nombre' => 'PEDERNALES' , 'idProvincia' => 13]);
        Canton::create(['nombre' => 'OLMEDO' , 'idProvincia' => 13]);
        Canton::create(['nombre' => 'PUERTO LÓPEZ' , 'idProvincia' => 13]);
        Canton::create(['nombre' => 'JAMA' , 'idProvincia' => 13]);
        Canton::create(['nombre' => 'JARAMIJÓ' , 'idProvincia' => 13]);
        Canton::create(['nombre' => 'SAN VICENTE' , 'idProvincia' => 13]);
        Canton::create(['nombre' => 'MORONA' , 'idProvincia' => 14]);
        Canton::create(['nombre' => 'GUALAQUIZA' , 'idProvincia' => 14]);
        Canton::create(['nombre' => 'LIMÓN INDANZA' , 'idProvincia' => 14]);
        Canton::create(['nombre' => 'PALORA' , 'idProvincia' => 14]);
        Canton::create(['nombre' => 'SANTIAGO' , 'idProvincia' => 14]);
        Canton::create(['nombre' => 'SUCÚA' , 'idProvincia' => 14]);
        Canton::create(['nombre' => 'HUAMBOYA' , 'idProvincia' => 14]);
        Canton::create(['nombre' => 'SAN JUAN BOSCO' , 'idProvincia' => 14]);
        Canton::create(['nombre' => 'TAISHA' , 'idProvincia' => 14]);
        Canton::create(['nombre' => 'LOGROÑO' , 'idProvincia' => 14]);
        Canton::create(['nombre' => 'PABLO SEXTO' , 'idProvincia' => 14]);
        Canton::create(['nombre' => 'TIWINTZA' , 'idProvincia' => 14]);
        Canton::create(['nombre' => 'TENA' , 'idProvincia' => 15]);
        Canton::create(['nombre' => 'ARCHIDONA' , 'idProvincia' => 15]);
        Canton::create(['nombre' => 'EL CHACO' , 'idProvincia' => 15]);
        Canton::create(['nombre' => 'QUIJOS' , 'idProvincia' => 15]);
        Canton::create(['nombre' => 'CARLOS JULIO AROSEMENA TOLA' , 'idProvincia' => 15]);
        Canton::create(['nombre' => 'PASTAZA' , 'idProvincia' => 16]);
        Canton::create(['nombre' => 'MERA' , 'idProvincia' => 16]);
        Canton::create(['nombre' => 'SANTA CLARA' , 'idProvincia' => 16]);
        Canton::create(['nombre' => 'ARAJUNO' , 'idProvincia' => 16]);
        Canton::create(['nombre' => 'QUITO' , 'idProvincia' => 17]);
        Canton::create(['nombre' => 'CAYAMBE' , 'idProvincia' => 17]);
        Canton::create(['nombre' => 'MEJIA' , 'idProvincia' => 17]);
        Canton::create(['nombre' => 'PEDRO MONCAYO' , 'idProvincia' => 17]);
        Canton::create(['nombre' => 'RUMIÑAHUI' , 'idProvincia' => 17]);
        Canton::create(['nombre' => 'SAN MIGUEL DE LOS BANCOS' , 'idProvincia' => 17]);
        Canton::create(['nombre' => 'PEDRO VICENTE MALDONADO' , 'idProvincia' => 17]);
        Canton::create(['nombre' => 'PUERTO QUITO' , 'idProvincia' => 17]);
        Canton::create(['nombre' => 'AMBATO' , 'idProvincia' => 18]);
        Canton::create(['nombre' => 'BAÑOS DE AGUA SANTA' , 'idProvincia' => 18]);
        Canton::create(['nombre' => 'CEVALLOS' , 'idProvincia' => 18]);
        Canton::create(['nombre' => 'MOCHA' , 'idProvincia' => 18]);
        Canton::create(['nombre' => 'PATATE' , 'idProvincia' => 18]);
        Canton::create(['nombre' => 'QUERO' , 'idProvincia' => 18]);
        Canton::create(['nombre' => 'SAN PEDRO DE PELILEO' , 'idProvincia' => 18]);
        Canton::create(['nombre' => 'SANTIAGO DE PÍLLARO' , 'idProvincia' => 18]);
        Canton::create(['nombre' => 'TISALEO' , 'idProvincia' => 18]);
        Canton::create(['nombre' => 'ZAMORA' , 'idProvincia' => 19]);
        Canton::create(['nombre' => 'CHINCHIPE' , 'idProvincia' => 19]);
        Canton::create(['nombre' => 'NANGARITZA' , 'idProvincia' => 19]);
        Canton::create(['nombre' => 'YACUAMBI' , 'idProvincia' => 19]);
        Canton::create(['nombre' => 'YANTZAZA (YANZATZA)' , 'idProvincia' => 19]);
        Canton::create(['nombre' => 'EL PANGUI' , 'idProvincia' => 19]);
        Canton::create(['nombre' => 'CENTINELA DEL CÓNDOR' , 'idProvincia' => 19]);
        Canton::create(['nombre' => 'PALANDA' , 'idProvincia' => 19]);
        Canton::create(['nombre' => 'PAQUISHA' , 'idProvincia' => 19]);
        Canton::create(['nombre' => 'SAN CRISTÓBAL' , 'idProvincia' => 20]);
        Canton::create(['nombre' => 'ISABELA' , 'idProvincia' => 20]);
        Canton::create(['nombre' => 'SANTA CRUZ' , 'idProvincia' => 20]);
        Canton::create(['nombre' => 'LAGO AGRIO' , 'idProvincia' => 21]);
        Canton::create(['nombre' => 'GONZALO PIZARRO' , 'idProvincia' => 21]);
        Canton::create(['nombre' => 'PUTUMAYO' , 'idProvincia' => 21]);
        Canton::create(['nombre' => 'SHUSHUFINDI' , 'idProvincia' => 21]);
        Canton::create(['nombre' => 'SUCUMBÍOS' , 'idProvincia' => 21]);
        Canton::create(['nombre' => 'CASCALES' , 'idProvincia' => 21]);
        Canton::create(['nombre' => 'CUYABENO' , 'idProvincia' => 21]);
        Canton::create(['nombre' => 'ORELLANA' , 'idProvincia' => 22]);
        Canton::create(['nombre' => 'AGUARICO' , 'idProvincia' => 22]);
        Canton::create(['nombre' => 'LA JOYA DE LOS SACHAS' , 'idProvincia' => 22]);
        Canton::create(['nombre' => 'LORETO' , 'idProvincia' => 22]);
        Canton::create(['nombre' => 'SANTO DOMINGO' , 'idProvincia' => 23]);
        Canton::create(['nombre' => 'SANTA ELENA' , 'idProvincia' => 24]);
        Canton::create(['nombre' => 'LA LIBERTAD' , 'idProvincia' => 24]);
        Canton::create(['nombre' => 'SALINAS' , 'idProvincia' => 24]);

    }
}
